Inception_V3: "checkpoints/trained_Inception_V3.pth"
ResNet50: "checkpoints/trained_ResNet50.pth"
DenseNet121: "checkpoints/trained_DenseNet121.pth"
ConvNeXt_Tiny: "checkpoints/trained_ConvNeXt_Tiny.pth"
KNN_Clustering: "checkpoints/default_KNN_Clustering.joblib"